name: Setup Rust
description: Install Rust toolchain with optional target and components

inputs:
  target:
    description: Target triple to install (optional)
    required: false
  components:
    description: Additional components to install (e.g., rustfmt, clippy)
    required: false

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.target }}
        components: ${{ inputs.components }}

    - name: Install musl-tools (Linux musl target)
      if: contains(inputs.target, 'musl')
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y musl-tools
